### ISSUE TITLE
官方合并这个修改了吗？

### ISSUE THREAD

**Issue by daiaji** [ptpt52/openwrt-openwrt#9]
我是想买路由 但是R7那边好像哀鸿遍野

**Comment by ptpt52** [comment]
什么意思？R7什么？

**Comment by daiaji** [comment]
@ptpt52  https://github.com/coolsnowwolf/lede.git
一些arch13 17用户貌似掉分区 没wifi比比皆是
看着618加券 arch17 ¥370挺好价的 想买
但是如果openwrt还是用不了就算了

**Comment by ptpt52** [comment]
那个不是官方好不好。
我的代码完全没问题
op官方是这个 https://github.com/openwrt/openwrt
我的代码是op官方基础的延伸

**Comment by daiaji** [comment]
@ptpt52 我是看到r7那年有出问题报告于是就没下单了 你这没有报告我也不清楚
老哥你有打算把这分支合并到官方吗？

**Comment by ptpt52** [comment]
固件下载地址 https://github.com/ptpt52/openwrt-openwrt/issues/6
合并openwrt官方 讨论中 https://github.com/openwrt/openwrt/pull/802

**Comment by daiaji** [comment]
@ptpt52 看到了
说起来这玩意刷了openwrt之后 2.4G大概穿几堵墙啊？
smzdm那边说这玩意信号不行

**Comment by ptpt52** [comment]
http://www.right.com.cn/forum/thread-268037-1-1.html

**Comment by daiaji** [comment]
@ptpt52 OK 我等恩山的评测吧
